In [88]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle as pk

In [89]:
models = []
acc = []
precision = []
recall = []
f1 = []

In [90]:
#importing HR train file
df = pd.read_csv('HR_train.csv')

In [91]:
#processing on test data
df2 = pd.read_csv('HR_test.csv')

In [92]:
df.shape
#df2.shape

(54808, 14)

In [93]:
df.isna().sum()


employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [94]:
df2.isna().sum()

employee_id                0
department                 0
region                     0
education               1034
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    1812
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
dtype: int64

In [95]:
#Null value imputation

In [96]:
missing_df = df.isnull().sum()
missing_df[missing_df.values != 0].index

Index(['education', 'previous_year_rating'], dtype='object')

In [97]:
def impute_cat(df, variable):
    # random sampling
    #df[variable] = df[variable]
        
    # extract the random sample to fill the na
    random_sample = df[variable].dropna().sample(df[variable].isnull().sum(), 
                                                 random_state=0)
    
    # pandas needs to have the same index in order to merge datasets
    random_sample.index = df[df[variable].isnull()].index
    
    df.loc[df[variable].isnull(), variable] = random_sample

In [98]:
def impute_num(df, variable):
    median = df[variable].median()
    df[variable] = df[variable].fillna(median)

In [99]:
#null value imputation for the train dataset
for col in missing_df[missing_df.values != 0].index:
    if(df[col].dtype == 'O'):
        impute_cat(df,col)
    else:
        impute_num(df, col)

In [100]:
#null value imputation for the Test dataset
for col in missing_df[missing_df.values != 0].index:
    if(df[col].dtype == 'O'):
        impute_cat(df2,col)
    else:
        impute_num(df2, col)

In [101]:
#categerical encoding

In [102]:
#encoding

prob_df = df.groupby(['department'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['dept_WOE'] = df.department.map(woe_labels)
df2['dept_WOE'] = df2.department.map(woe_labels)

In [103]:
prob_df = df.groupby(['region'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['region_WOE'] = df.region.map(woe_labels)
df2['region_WOE'] = df2.region.map(woe_labels)

In [104]:
prob_df = df.groupby(['education'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['education_WOE'] = df.education.map(woe_labels)
df2['education_WOE'] = df2.education.map(woe_labels)

In [105]:
prob_df = df.groupby(['gender'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['gender_WOE'] = df.gender.map(woe_labels)
df2['gender_WOE'] = df2.gender.map(woe_labels)

In [106]:
prob_df = df.groupby(['recruitment_channel'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['recruitment_channel_WOE'] = df.recruitment_channel.map(woe_labels)
df2['recruitment_channel_WOE'] = df2.recruitment_channel.map(woe_labels)


In [107]:
prob_df = df.groupby(['no_of_trainings'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['trainings_WOE'] = df.no_of_trainings.map(woe_labels)
df2['trainings_WOE'] = df2.no_of_trainings.map(woe_labels)

In [108]:
prob_df = df.groupby(['avg_training_score'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['avg_training_score_WOE'] = df.avg_training_score.map(woe_labels)
df2['avg_training_score_WOE'] = df2.avg_training_score.map(woe_labels)

In [109]:
df.head(1)

employee_id         department    region         education gender  \
0        65438  Sales & Marketing  region_7  Master's & above      f   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   

   length_of_service           ...            awards_won?  avg_training_score  \
0                  8           ...                      0                  49   

   is_promoted  dept_WOE  region_WOE  education_WOE  gender_WOE  \
0            0 -2.555904   -2.126523      -2.235082   -2.314444   

   recruitment_channel_WOE  trainings_WOE  avg_training_score_WOE  
0                -2.376107      -2.336974               -3.250762  

[1 rows x 21 columns]

In [110]:
del df['department']
del df['region']
del df['education']
del df['gender']
del df['recruitment_channel']
del df['no_of_trainings']
del df['avg_training_score']
del df2['department']
del df2['region']
del df2['education']
del df2['gender']
del df2['recruitment_channel']
del df2['no_of_trainings']
del df2['avg_training_score']
del df['employee_id']
del df2['employee_id']

In [111]:
#feature Scaling

In [113]:
X = df.iloc[:, [0,1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12]].values
y = df.iloc[:, 5].values

X2 = df2.iloc[:].values

In [114]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, 
                                                    random_state = 45)

In [115]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [116]:
cols = df.columns.difference(['is_promoted'])

In [117]:
#feature selection
from sklearn.ensemble import RandomForestClassifier
def feature_select(X, y, cols, cutoff):
    Classifier = RandomForestClassifier(n_estimators = 150, random_state = 0)
    Classifier.fit(X, y)
    feat_imps = pd.concat([pd.DataFrame(cols, columns=['Features']),
                       pd.DataFrame(Classifier.feature_importances_, columns=['Importances'])],
                     axis=1)
    feat_imps = feat_imps.sort_values(['Importances'], ascending=False)
    feat_imps['Cumulative Importances'] = feat_imps['Importances'].cumsum()
    feat_imps = feat_imps[feat_imps['Cumulative Importances'] < cutoff]
    return feat_imps['Features'].tolist() 

In [118]:
imp_cols = feature_select(X, y, cols, 0.990)

In [119]:
imp_cols

['trainings_WOE',
 'KPIs_met >80%',
 'gender_WOE',
 'avg_training_score_WOE',
 'education_WOE',
 'age',
 'awards_won?',
 'recruitment_channel_WOE',
 'dept_WOE',
 'region_WOE',
 'previous_year_rating']

In [120]:
X=df[imp_cols].values
y = df.iloc[:, 5].values
X2=df2[imp_cols].values

In [121]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, 
                                                    random_state = 5)

In [122]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X2=sc.transform(X2)


In [123]:
# Smote ho rha hai 
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=2)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel())
X_test_res, y_test_res = sm.fit_sample(X_test, y_test.ravel())

In [124]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [125]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = 'entropy', 
                            max_depth= 3,
                            random_state = 2)
dt.fit(X_train_res, y_train_res)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=2,
            splitter='best')

In [126]:
print('Confusion Matrix for DTrees: \n',confusion_matrix(y_test_res, dt.predict(X_test_res)))
print('Accuracy for DTrees: \n',accuracy_score(y_test_res, dt.predict(X_test_res)))
acc.append(accuracy_score(y_test_res, dt.predict(X_test_res)))
print('Precision for DTrees: \n',precision_score(y_test_res, dt.predict(X_test_res)))
precision.append(precision_score(y_test_res, dt.predict(X_test_res)))
print('Recall for DTrees: \n',recall_score(y_test_res, dt.predict(X_test_res)))
recall.append(recall_score(y_test_res, dt.predict(X_test_res)))
print('f1_score for DTrees: \n',f1_score(y_test_res, dt.predict(X_test_res)))
f1.append(f1_score(y_test_res, dt.predict(X_test_res)))

Confusion Matrix for DTrees: 
 [[ 9822  5227]
 [ 2067 12982]]
Accuracy for DTrees: 
 0.7576583161671872
Precision for DTrees: 
 0.7129441484979955
Recall for DTrees: 
 0.8626486809754801
f1_score for DTrees: 
 0.7806843466233688


In [127]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 11, criterion = 'entropy', 
                                    random_state = 0)
rf.fit(X_train_res, y_train_res)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=11, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [128]:
print('Confusion Matrix for RF: \n',confusion_matrix(y_test_res, rf.predict(X_test_res)))
print('Accuracy for RF: \n',accuracy_score(y_test_res, rf.predict(X_test_res)))
acc.append(accuracy_score(y_test_res, rf.predict(X_test_res)))
print('Precision for RF: \n',precision_score(y_test_res, rf.predict(X_test_res)))
precision.append(precision_score(y_test_res, rf.predict(X_test_res)))
print('Recall for RF: \n',recall_score(y_test_res, rf.predict(X_test_res)))
recall.append(recall_score(y_test_res, rf.predict(X_test_res)))
print('f1_score for RF: \n',f1_score(y_test_res, rf.predict(X_test_res)))
f1.append(f1_score(y_test_res, rf.predict(X_test_res)))

Confusion Matrix for RF: 
 [[14552   497]
 [ 2630 12419]]
Accuracy for RF: 
 0.896106053558376
Precision for RF: 
 0.9615205946113348
Recall for RF: 
 0.8252375573127783
f1_score for RF: 
 0.8881816556409798


In [129]:
from sklearn.ensemble import AdaBoostClassifier
adb = AdaBoostClassifier(base_estimator=rf, n_estimators=31, 
                         algorithm='SAMME.R', random_state=40)
adb.fit(X_train_res, y_train_res)

AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=11, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False),
          learning_rate=1.0, n_estimators=31, random_state=40)

In [130]:
print('Confusion Matrix for RF: \n',confusion_matrix(y_test_res, rf.predict(X_test_res)))
print('Accuracy for RF: \n',accuracy_score(y_test_res, rf.predict(X_test_res)))
acc.append(accuracy_score(y_test_res, rf.predict(X_test_res)))
print('Precision for RF: \n',precision_score(y_test_res, rf.predict(X_test_res)))
precision.append(precision_score(y_test_res, rf.predict(X_test_res)))
print('Recall for RF: \n',recall_score(y_test_res, rf.predict(X_test_res)))
recall.append(recall_score(y_test_res, rf.predict(X_test_res)))
print('f1_score for RF: \n',f1_score(y_test_res, rf.predict(X_test_res)))
f1.append(f1_score(y_test_res, rf.predict(X_test_res)))

Confusion Matrix for RF: 
 [[14552   497]
 [ 2630 12419]]
Accuracy for RF: 
 0.896106053558376
Precision for RF: 
 0.9615205946113348
Recall for RF: 
 0.8252375573127783
f1_score for RF: 
 0.8881816556409798


In [131]:
final=adb.predict(X2)

In [132]:
pd.DataFrame(final).to_csv("predicted4.csv",header=None, index=False)