In [396]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle as pk

In [397]:
models = []
acc = []
precision = []
recall = []
f1 = []

In [398]:
#importing HR train file
df = pd.read_csv('HR_train.csv')

In [399]:
#processing on test data
df2 = pd.read_csv('HR_test.csv')

In [400]:
df.shape
#df2.shape

(54808, 14)

In [401]:
df.isna().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [402]:
df2.isna().sum()

employee_id                0
department                 0
region                     0
education               1034
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    1812
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
dtype: int64

In [403]:
 # let's create a variable to replace NA with a random sample

def impute_na(df, variable):
    # random sampling
    #df[variable] = df[variable]
        
    # extract the random sample to fill the na
    random_sample = df[variable].dropna().sample(df[variable].isnull().sum(), 
                                                 random_state=0)
    
    # pandas needs to have the same index in order to merge datasets
    random_sample.index = df[df[variable].isnull()].index
    
    df.loc[df[variable].isnull(), variable] = random_sample

In [404]:
impute_na(df,'education')

In [405]:
impute_na(df2,'education')

In [406]:
df['previous_year_rating'] = df['previous_year_rating'].fillna(0) 

In [407]:
df2['previous_year_rating'] = df2['previous_year_rating'].fillna(0) 

In [408]:
#df.isna().sum()
df2.isna().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
dtype: int64

In [409]:
df.isna().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [413]:
#columns_WOE=df.columns[1:-2]
#columns_WOE
#from category_encoders import WOEEncoder
#woe_enc=WOEEncoder(cols=columns_WOE,random_state=17).fit(X_train,y_train)

In [414]:
#encoding

prob_df = df.groupby(['department'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['dept_WOE'] = df.department.map(woe_labels)
df2['dept_WOE'] = df2.department.map(woe_labels)

In [415]:
prob_df = df.groupby(['region'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['region_WOE'] = df.region.map(woe_labels)
df2['region_WOE'] = df2.region.map(woe_labels)

In [418]:
prob_df = df.groupby(['education'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['education_WOE'] = df.education.map(woe_labels)
df2['education_WOE'] = df2.education.map(woe_labels)

In [421]:
prob_df = df.groupby(['gender'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['gender_WOE'] = df.gender.map(woe_labels)
df2['gender_WOE'] = df2.gender.map(woe_labels)

In [422]:
prob_df = df.groupby(['recruitment_channel'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['recruitment_channel_WOE'] = df.recruitment_channel.map(woe_labels)
df2['recruitment_channel_WOE'] = df2.recruitment_channel.map(woe_labels)


In [425]:
prob_df = df.groupby(['no_of_trainings'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['trainings_WOE'] = df.no_of_trainings.map(woe_labels)
df2['trainings_WOE'] = df2.no_of_trainings.map(woe_labels)

In [429]:
prob_df = df.groupby(['avg_training_score'])['is_promoted'].mean()
prob_df = pd.DataFrame(prob_df)
prob_df['Not_promoted'] = 1-prob_df.is_promoted


prob_df.loc[prob_df['is_promoted'] == 0, 'is_promoted'] = 0.00001
prob_df.loc[prob_df['Not_promoted'] == 0, 'Not_promoted'] = 0.00001

prob_df['WoE'] = np.log(prob_df['is_promoted']/prob_df['Not_promoted'])

woe_labels = prob_df['WoE'].to_dict()

df['avg_training_score_WOE'] = df.avg_training_score.map(woe_labels)
df2['avg_training_score_WOE'] = df2.avg_training_score.map(woe_labels)

In [437]:
df.head()

age  previous_year_rating  length_of_service  KPIs_met >80%  awards_won?  \
0   35                   5.0                  8              1            0   
1   30                   5.0                  4              0            0   
2   34                   3.0                  7              0            0   
3   39                   1.0                 10              0            0   
4   45                   3.0                  2              0            0   

   is_promoted  dept_WOE  region_WOE  education_WOE  gender_WOE  \
0            0 -2.555904   -2.126523      -2.235082   -2.314444   
1            0 -2.311829   -2.048659      -2.435100   -2.400278   
2            0 -2.555904   -2.740231      -2.435100   -2.400278   
3            0 -2.555904   -2.025070      -2.435100   -2.400278   
4            0 -2.115565   -2.694911      -2.435100   -2.400278   

   recruitment_channel_WOE  trainings_WOE  avg_training_score_WOE  
0                -2.376107      -2.336974               -3.250762  
1                -2.389825      -2.336974               -2.682113  
2                -2.376107      -2.336974               -3.146305  
3                -2.389825      -2.501571               -3.146305  
4                -2.389825      -2.336974               -2.062347

In [432]:
del df['department']
del df['region']
del df['education']
del df['gender']
del df['recruitment_channel']
del df['no_of_trainings']
del df['avg_training_score']
del df2['department']
del df2['region']
del df2['education']
del df2['gender']
del df2['recruitment_channel']
del df2['no_of_trainings']
del df2['avg_training_score']

In [435]:
del df['employee_id']
del df2['employee_id']

In [438]:
df.head()

age  previous_year_rating  length_of_service  KPIs_met >80%  awards_won?  \
0   35                   5.0                  8              1            0   
1   30                   5.0                  4              0            0   
2   34                   3.0                  7              0            0   
3   39                   1.0                 10              0            0   
4   45                   3.0                  2              0            0   

   is_promoted  dept_WOE  region_WOE  education_WOE  gender_WOE  \
0            0 -2.555904   -2.126523      -2.235082   -2.314444   
1            0 -2.311829   -2.048659      -2.435100   -2.400278   
2            0 -2.555904   -2.740231      -2.435100   -2.400278   
3            0 -2.555904   -2.025070      -2.435100   -2.400278   
4            0 -2.115565   -2.694911      -2.435100   -2.400278   

   recruitment_channel_WOE  trainings_WOE  avg_training_score_WOE  
0                -2.376107      -2.336974               -3.250762  
1                -2.389825      -2.336974               -2.682113  
2                -2.376107      -2.336974               -3.146305  
3                -2.389825      -2.501571               -3.146305  
4                -2.389825      -2.336974               -2.062347

In [445]:
X = df.iloc[:, [0,1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12]].values
y = df.iloc[:, 5].values

X2 = df.iloc[:].values
#y = df.iloc[:, 13].values

In [446]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, 
                                                    random_state = 0)

In [447]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
#scaling for test model is pending

In [451]:
df.head()

age  previous_year_rating  length_of_service  KPIs_met >80%  awards_won?  \
0   35                   5.0                  8              1            0   
1   30                   5.0                  4              0            0   
2   34                   3.0                  7              0            0   
3   39                   1.0                 10              0            0   
4   45                   3.0                  2              0            0   

   is_promoted  dept_WOE  region_WOE  education_WOE  gender_WOE  \
0            0 -2.555904   -2.126523      -2.235082   -2.314444   
1            0 -2.311829   -2.048659      -2.435100   -2.400278   
2            0 -2.555904   -2.740231      -2.435100   -2.400278   
3            0 -2.555904   -2.025070      -2.435100   -2.400278   
4            0 -2.115565   -2.694911      -2.435100   -2.400278   

   recruitment_channel_WOE  trainings_WOE  avg_training_score_WOE  
0                -2.376107      -2.336974               -3.250762  
1                -2.389825      -2.336974               -2.682113  
2                -2.376107      -2.336974               -3.146305  
3                -2.389825      -2.501571               -3.146305  
4                -2.389825      -2.336974               -2.062347

In [485]:
cols = df.columns.difference(['is_promoted'])

In [486]:
cols

Index(['KPIs_met >80%', 'age', 'avg_training_score_WOE', 'awards_won?',
       'dept_WOE', 'education_WOE', 'gender_WOE', 'length_of_service',
       'previous_year_rating', 'recruitment_channel_WOE', 'region_WOE',
       'trainings_WOE'],
      dtype='object')

In [487]:
#feature selection
from sklearn.ensemble import RandomForestClassifier
def feature_select(X, y, cols, cutoff):
    Classifier = RandomForestClassifier(n_estimators = 150, random_state = 0)
    Classifier.fit(X, y)
    feat_imps = pd.concat([pd.DataFrame(cols, columns=['Features']),
                       pd.DataFrame(Classifier.feature_importances_, columns=['Importances'])],
                     axis=1)
    feat_imps = feat_imps.sort_values(['Importances'], ascending=False)
    feat_imps['Cumulative Importances'] = feat_imps['Importances'].cumsum()
    feat_imps = feat_imps[feat_imps['Cumulative Importances'] < cutoff]
    return feat_imps['Features'].tolist() 

In [488]:
imp_cols = feature_select(X, y, cols, 0.990)

In [489]:
imp_cols


['trainings_WOE',
 'KPIs_met >80%',
 'gender_WOE',
 'avg_training_score_WOE',
 'education_WOE',
 'age',
 'awards_won?',
 'recruitment_channel_WOE',
 'dept_WOE',
 'region_WOE',
 'previous_year_rating']

In [491]:
X=df[imp_cols].values
y = df.iloc[:, 5].values

In [492]:
X  

array([[-2.33697416,  1.        , -2.31444361, ..., -2.55590356,
        -2.12652297,  5.        ],
       [-2.33697416,  0.        , -2.40027805, ..., -2.31182865,
        -2.04865924,  5.        ],
       [-2.33697416,  0.        , -2.40027805, ..., -2.55590356,
        -2.7402312 ,  3.        ],
       ...,
       [-2.33697416,  1.        , -2.40027805, ..., -2.24634537,
        -2.25310504,  5.        ],
       [-2.33697416,  0.        , -2.40027805, ..., -2.55590356,
        -3.94158181,  1.        ],
       [-2.33697416,  0.        , -2.40027805, ..., -2.82015264,
        -2.04865924,  1.        ]])

In [493]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, 
                                                    random_state = 5)

In [494]:
X_test

array([[-2.33697416,  0.        , -2.40027805, ..., -2.31182865,
        -2.04865924,  4.        ],
       [-2.33697416,  1.        , -2.40027805, ..., -2.24634537,
        -2.51274145,  5.        ],
       [-2.33697416,  0.        , -2.40027805, ..., -2.31182865,
        -2.44063105,  2.        ],
       ...,
       [-2.33697416,  0.        , -2.40027805, ..., -2.31182865,
        -2.79404065,  1.        ],
       [-2.50157143,  1.        , -2.31444361, ..., -2.11556502,
        -2.04865924,  5.        ],
       [-2.33697416,  0.        , -2.31444361, ..., -2.31182865,
        -2.45519018,  3.        ]])

In [495]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
#scaling for test model is pending

In [496]:
# Smote nahi ho rha hai 

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=2)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel())
X_test_res, y_test_res = sm.fit_sample(X_test, y_test.ravel())

In [497]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 0)
lr.fit(X_train_res, y_train_res)
models.append('Logistic Regression HR Analytics')

C:\Users\Barnali PC\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [498]:
from sklearn.metrics import (confusion_matrix, accuracy_score, precision_score, 
                             recall_score, f1_score)

In [499]:
print('Confusion Matrix for LR: \n',confusion_matrix(y_test, lr.predict(X_test)))
print('Accuracy for LR: \n',accuracy_score(y_test, lr.predict(X_test)))
acc.append(accuracy_score(y_test, lr.predict(X_test)))
print('Precision for LR: \n',precision_score(y_test, lr.predict(X_test)))
precision.append(precision_score(y_test, lr.predict(X_test)))
print('Recall for LR: \n',recall_score(y_test, lr.predict(X_test)))
recall.append(recall_score(y_test, lr.predict(X_test)))
print('f1_score for LR: \n',f1_score(y_test, lr.predict(X_test)))
f1.append(f1_score(y_test, lr.predict(X_test)))

Confusion Matrix for LR: 
 [[11012  4037]
 [  362  1032]]
Accuracy for LR: 
 0.7324697439639969
Precision for LR: 
 0.20359045176563426
Recall for LR: 
 0.7403156384505022
f1_score for LR: 
 0.31935633606684205


In [500]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = 'entropy', 
                            max_depth=4 ,
                            random_state = 0)
dt.fit(X_train_res, y_train_res)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [501]:
print('Confusion Matrix for DTrees: \n',confusion_matrix(y_test_res, dt.predict(X_test_res)))
print('Accuracy for DTrees: \n',accuracy_score(y_test_res, dt.predict(X_test_res)))
acc.append(accuracy_score(y_test_res, dt.predict(X_test_res)))
print('Precision for DTrees: \n',precision_score(y_test_res, dt.predict(X_test_res)))
precision.append(precision_score(y_test_res, dt.predict(X_test_res)))
print('Recall for DTrees: \n',recall_score(y_test_res, dt.predict(X_test_res)))
recall.append(recall_score(y_test_res, dt.predict(X_test_res)))
print('f1_score for DTrees: \n',f1_score(y_test_res, dt.predict(X_test_res)))
f1.append(f1_score(y_test_res, dt.predict(X_test_res)))

Confusion Matrix for DTrees: 
 [[11081  3968]
 [ 2924 12125]]
Accuracy for DTrees: 
 0.7710146853611536
Precision for DTrees: 
 0.7534331697011123
Recall for DTrees: 
 0.8057013755066782
f1_score for DTrees: 
 0.7786911566373387


In [502]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 11, criterion = 'entropy', 
                                    random_state = 0)
rf.fit(X_train_res, y_train_res)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=11, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [503]:
print('Confusion Matrix for RF: \n',confusion_matrix(y_test_res, rf.predict(X_test_res)))
print('Accuracy for RF: \n',accuracy_score(y_test_res, rf.predict(X_test_res)))
acc.append(accuracy_score(y_test_res, rf.predict(X_test_res)))
print('Precision for RF: \n',precision_score(y_test_res, rf.predict(X_test_res)))
precision.append(precision_score(y_test_res, rf.predict(X_test_res)))
print('Recall for RF: \n',recall_score(y_test_res, rf.predict(X_test_res)))
recall.append(recall_score(y_test_res, rf.predict(X_test_res)))
print('f1_score for RF: \n',f1_score(y_test_res, rf.predict(X_test_res)))
f1.append(f1_score(y_test_res, rf.predict(X_test_res)))

Confusion Matrix for RF: 
 [[14540   509]
 [ 2615 12434]]
Accuracy for RF: 
 0.8962057279553459
Precision for RF: 
 0.9606737232480878
Recall for RF: 
 0.8262343012824772
f1_score for RF: 
 0.8883966847670763


In [506]:
from sklearn.ensemble import AdaBoostClassifier
adb = AdaBoostClassifier(base_estimator=dt, n_estimators=15, 
                         algorithm='SAMME.R', random_state=40)
adb.fit(X_train_res, y_train_res)

AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best'),
          learning_rate=1.0, n_estimators=15, random_state=40)

In [507]:
print('Confusion Matrix for Adaboost: \n',confusion_matrix(y_test_res, adb.predict(X_test_res)))
print('Accuracy for Adaboost: \n',accuracy_score(y_test_res, adb.predict(X_test_res)))
acc.append(accuracy_score(y_test_res, adb.predict(X_test_res)))
print('Precision for Adaboost: \n',precision_score(y_test_res, adb.predict(X_test_res)))
precision.append(precision_score(y_test_res, adb.predict(X_test_res)))
print('Recall for Adaboost: \n',recall_score(y_test_res, adb.predict(X_test_res)))
recall.append(recall_score(y_test_res,adb.predict(X_test_res)))
print('f1_score for Adaboost: \n',f1_score(y_test_res, adb.predict(X_test_res)))
f1.append(f1_score(y_test_res, adb.predict(X_test_res)))

Confusion Matrix for Adaboost: 
 [[14372   677]
 [ 1303 13746]]
Accuracy for Adaboost: 
 0.9342148979998671
Precision for Adaboost: 
 0.9530610829924426
Recall for Adaboost: 
 0.9134161738321483
f1_score for Adaboost: 
 0.9328175895765473


In [508]:
# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
parameters = {"n_estimators": [15, 20, 25],
              "criterion":['gini','entropy'],
              "max_depth": [4, 6, 8],
              "min_samples_split": [10, 20, 30],
              "min_samples_leaf": [1, 5, 15],
              "min_weight_fraction_leaf": [0.1, 0.05, 0.005]}
grid_search = GridSearchCV(estimator = rf,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)

In [509]:
grid_search.fit(X_train_res, y_train_res)

GridSearchCV(cv=10, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=11, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'n_estimators': [15, 20, 25], 'criterion': ['gini', 'entropy'], 'max_depth': [4, 6, 8], 'min_samples_split': [10, 20, 30], 'min_samples_leaf': [1, 5, 15], 'min_weight_fraction_leaf': [0.1, 0.05, 0.005]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [510]:
best_parameters = grid_search.best_params_
best_parameters

{'criterion': 'entropy',
 'max_depth': 8,
 'min_samples_leaf': 1,
 'min_samples_split': 10,
 'min_weight_fraction_leaf': 0.005,
 'n_estimators': 25}

In [511]:
    # Fitting Final Model on training set
from sklearn.ensemble import RandomForestClassifier
tunedRF = RandomForestClassifier(n_estimators = best_parameters["n_estimators"],
                                 criterion = best_parameters["criterion"],
                                 max_depth = best_parameters["max_depth"],
                                 min_samples_split = best_parameters["min_samples_split"],
                                 min_samples_leaf = best_parameters["min_samples_leaf"],
                                 min_weight_fraction_leaf = best_parameters["min_weight_fraction_leaf"])
tunedRF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=8, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=10,
            min_weight_fraction_leaf=0.005, n_estimators=25, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [512]:
print('Confusion Matrix for Tuned RF: \n',confusion_matrix(y_test, tunedRF.predict(X_test)))
print('Accuracy for Tuned RF: \n',accuracy_score(y_test, tunedRF.predict(X_test)))
acc.append(accuracy_score(y_test, tunedRF.predict(X_test)))
print('Precision for Tuned RF: \n',precision_score(y_test, tunedRF.predict(X_test)))
precision.append(precision_score(y_test, tunedRF.predict(X_test)))
print('Recall for Tuned RF: \n',recall_score(y_test, tunedRF.predict(X_test)))
recall.append(recall_score(y_test, tunedRF.predict(X_test)))
print('f1_score for Tuned RF: \n',f1_score(y_test, tunedRF.predict(X_test)))
f1.append(f1_score(y_test, tunedRF.predict(X_test)))

Confusion Matrix for Tuned RF: 
 [[15036    13]
 [ 1249   145]]
Accuracy for Tuned RF: 
 0.9232500152040382
Precision for Tuned RF: 
 0.9177215189873418
Recall for Tuned RF: 
 0.10401721664275466
f1_score for Tuned RF: 
 0.18685567010309279
